export const ACCOUNTING_TEXT = {
  sidebar: {
    taxRegister: "Đăng ký mã số thuế",
    declarationDependent: "Đăng ký người phụ thuộc",
    taxPeriod: "Khai thuế theo kỳ",
    taxDeduction: "Chứng từ khấu trừ thuế",
    taxSettlement: "Quyết toán thuế",
    taxProcedure: "Thủ tục",
    taxReport: "Báo cáo",
    employee: "Người nộp thuế",
    tvanService: "Đăng ký dịch vụ thuế",
    options: "Thiết lập",
    trash: "Thùng rác",
    resize: "Thu gọn",
    televisonManagement: "Quản lý mặt hàng tivi",
    conditonerManagement: "Quản lý mặt hàng điều hòa",
    washingMachineManagement: "Quản lý mặt hàng máy giặt",
    riceCookerManagement: "Quản lý mặt hàng nồi cơm",
  },
  words: {
    TelevisonViewTitle: "Quản lý mặt hàng tivi",
    ManagementViewTitle: "Quản lý lao động | AMIS Thuế TNCN",
    Notification: "Thông báo",
    Help: "Trợ giúp",
    OtherFeature: "Tính năng khác",
    Using: "Sử dụng",
    Warning: "Cảnh báo",
    OpenInNewTab: "Mở trên cửa số mới",
    TotalRecord: (total) => `Tổng số: <b>${total}</b> bản ghi`,
    ClearFilter: "Bỏ lọc",
    Apply: "Áp dụng",
    Time: "Thời gian",
    FromDate: "Từ ngày:",
    ToDate: "Đến ngày:",
    HavingTaxCode: "Đã có MST",
    NotHavingTaxCode: "Chưa có MST",
    Employee: "Nhân viên",
    Guest: "Vãng lai",
    GetInformation: "Lấy thông tin",
    ModifyColumn: "Tùy chỉnh cột",
    Default: "Mặc định",
    Yes: "Có",
    No: "Không",
    Add: "Thêm",
    Close: "Đóng",
    Accept: "Đồng ý",
    Cancel: "Hủy",
    Save: "Lưu",
    NotSave: "Không lưu",
    Delete: "Xóa",
    Modify: "Chỉnh sửa",
    SaveAndContinue: "Lưu & Thêm mới",
    employeeViewTitle: "Hồ sơ người nộp thuế",
    manageLicense: "Quản lý lao động sử dụng dịch vụ",
    setUpAutoRules: "Thiết lập quy tắc tự động",
    totalWorkers: "Tổng số lao động",
    totalWorkersSub:
      "Tất cả người nộp thuế có loại đối tượng là Nhân viên và Vãng lai trên AMIS Thuế TNCN",
    usingWorkers: "Đang sử dụng dịch vụ",
    usingWorkersSub:
      "Tất cả người nộp thuế có loại đối tượng là Nhân viên và Vãng lai trên AMIS Thuế TNCN",
    stopWorkers: "Không sử dụng dịch vụ",
    stopWorkersSub:
      "Người nộp thuế có loại đối tượng là Nhân viên và Vãng lai không thiết lập sử dụng dịch vụ Thuế TNCN",
    export: "Xuất khẩu",
    addNew: "Thêm mới",
    NoFamilyInformation: "Không có thông tin gia đình",
    GeneralInformation: "Thông tin chung",
    PersonalInformation: "Thông tin cá nhân",
    NativePlace: "Hộ khẩu thường trú",
    CurrentPlace: "Chỗ ở hiện nay",
    DeductionInfo: "Thông tin giảm trừ",
    LikeNativePlace: "Giống hộ khẩu thường trú",
    WorkInformation: "Thông tin công việc",
    FamilyInfomartion: "Thông tin gia đình",
    CreateFamilyMember: "Thêm thành viên gia đình",
    UpdateFamilyMember: "Sửa thành viên gia đình",
    CreateEmployee: "Thêm người nộp thuế",
    UpdateEmployee: "Sửa người nộp thuế",
    BirthInformation: "THÔNG TIN KHAI SINH",
    Male: "Nam",
    Female: "Nữ",
    EmployeeInformation: "Thông tin người nộp thuế",
    StopUsing: "Ngừng sử dụng",
    Import: "Nhập khẩu",
    CreateEmployeeSuccess: "Thêm sản phẩm thành công!",
    UpdateEmployeeSuccess: "Cập nhật sảm phẩm thành công!",
    NoDataText: "Không có dữ liệu hợp lệ",
    SaveChanges: "Lưu lại những thay đổi?",
    IsWorking: "Đang làm việc",
    NotWorking: "Đã nghỉ việc",
    Filter: "Bộ lọc",
  },

  headers: {
    EmployeeType: "Loại đối tượng",
    EmployeeCode: "Mã nhân viên",
    FullName: "Họ và tên",
    DateOfBirth: "Ngày sinh",
    Gender: "Giới tính",
    PhoneNumber: "Số điện thoại",
    Email: "Email",
    TaxCode: "Mã số thuế",
    DocumentType: "Loại giấy tờ",
    IdentityNumber: "Số CMND/CCCD/Hộ chiếu",
    IdentityDate: "Ngày cấp",
    IdentityPlace: "Nơi cấp",
    Nationality: "Quốc tịch",
    ContractType: "Loại hợp đồng",
    Department: "Bộ phận/Phòng ban",
    WorkPosition: "Vị trí/Chức vụ",
    WorkStatus: "Trạng thái",
    InternshipDate: "Ngày học việc",
    ProbationDate: "Ngày thử việc",
    OfficialDate: "Ngày chính thức",
    ResignDate: "Ngày thử việc",
  },
  errors: {
    requiredEmployeeCodeError: "Mã người nộp thuế không được bỏ trống",
    requiredFullNameError: "Họ tên không được bỏ trống",
    requiredIdentityNumberError:
      "Không nhập Mã số thuế thì Số CMND/CCCD/Hộ chiếu không được bỏ trống",
    requiredIdentityDateError:
      "Không nhập Mã số thuế thì Ngày cấp không được bỏ trống",
    requiredIdentityPlaceError:
      "Không nhập Mã số thuế thì Nơi cấp không được bỏ trống",
    requiredWorkPositionError: "Vị trí công việc không được bỏ trống",
    requiredRelationshipError: "Quan hệ không được bỏ trống",
    InvalidEmail: "Email không hợp lệ",
    InvalidIdentityNumber: "Số CMND/CCCD không đúng định dạng",
    InvalidPhoneNumber: "Số CMND/CCCD không đúng định dạng",
  },
  Message: {
    DeleteEmployeeSuccess: "Xóa bản ghi thành công!",
    DeleteFamilySuccess: "Xóa thành viên gia đình thành công!",
    UpdateStatusSuccess: "Cập nhật trạng thái thành công",
    SystemError: "Lỗi hệ thống",
    SearchByConditions:
      "Tìm theo Mã/Tên nhân viên, mã số thuế, chứng minh nhân dân",
  },
  WarningTitle: {
    DeleteData: "Xóa dữ liệu",
    DeleteEmployee: "Xóa người nộp thuế",
    SaveChanges: "Dữ liệu đã thay đổi",
  },
  Warning: {
    DeleteFamilyInfo:
      "Bạn có chắc chắn xóa thông tin gia đình này khỏi danh sách không?",
    DeleteManyEmployee: (total) =>
      `Bạn có chắc chắn muốn xóa <b>(${total})</b> sản phẩm vào Thùng rác?`,
    DeleteEmployee: (name) =>
      `Bạn có chắc chắn muốn xóa bản ghi <b>${name}</b>?`,
  },
  Label: {
    Note: "Ghi chú",
    IsDependant: "Là người phụ thuộc",
    MonthDeductionStart: "Giảm trừ từ tháng",
    MonthDeductionEnd: "Giảm trừ đến tháng",
    EmployeeCode: "Mã người nộp thuế",
    FullName: "Họ tên",
    DateOfBirth: "Ngày sinh",
    Gender: "Giới tính",
    PhoneNumber: "Số điện thoại",
    Email: "Email",
    TaxCode: "Mã số thuế",
    DocumentType: "Loại giấy tờ",
    IdentityDate: "Ngày cấp",
    IdentityPlace: "Nơi cấp",
    Nationality: "Quốc tịch",
    ContractType: "Loại hợp đồng",
    Nation: "Quốc gia",
    Province: "Tỉnh/Thành phố",
    District: "Quận/huyện",
    Ward: "Xã/phường",
    StreetHouseNumber: "Số nhà, đường/phố, thôn/xóm",
    Address: "Địa chỉ",
    Department: "Bộ phận/phòng ban",
    WorkPosition: "Vị trí công việc",
    Title: "Chức danh",
    InternshipDate: "Ngày học việc",
    ProbationDate: "Ngày thử việc",
    OfficialDate: "Ngày chính thức",
    ResignDate: "Ngày nghỉ việc",
    WorkStatus: "Trạng thái làm việc",
    FamilyMemberName: "Họ tên thành viên",
    Relationship: "Quan hệ",
    IdentityNumber: "Số CMND",
    BirthCode: "Số khai sinh",
    BirthNotebook: "Quyển sổ",
    CertificateDate: "Ngày cấp giấy khai sinh",
    EmployeeType: "Loại đối tượng",
    CitizenCard: "Số CCCD",
    Passport: "Số hộ chiếu",
  },
  Placeholder: {
    EmployeeCode: "Nhập mã người nộp thuế",
    FullName: "Nhập họ tên",
    PhoneNumber: "Nhập số điện thoại",
    Email: "Nhập email",
    TaxCode: "Nhập mã số thuế",
    IdentityNumber: "Nhập số CMND/CCCD/Hộ chiếu",
    IdentityPlace: "Chọn/nhập nơi cấp",
    Province: "Chọn/nhập tỉnh/thành phố",
    District: "Chọn/nhập quận/huyện",
    Ward: "Chọn/nhập xã/phường",
    StreetHouseNumber: "Nhập số nhà, đường/phố, thôn/xóm",
    WorkPosition: "Chọn/nhập vị trí công việc",
    BirthCode: "Nhập số khai sinh",
    BirthNotebook: "Nhập quyển sổ",
    Search: "Tìm kiếm",
    Department: "Bộ phận/phòng ban",
    SearchByConditions: "Tìm theo Mã/Tên nhân viên, MST, CMND",
    UsingStatus: "Trạng thái sử dụng",
  },
};

export const ENUMS = {
  DocumentType: {
    IdentityNumber: 1,
    CitizenCard: 2,
  },
};
