--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 8/10/2024 3:54:03 PM
-- Server version: 8.0.32
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO pico.dieuhoa(ID, ProductName, ProductBrand, ProductPrice, ProductSize, ProductOrigin, ProductMaterial, ProductYear, ProductWeight, ProductQuantity, ProductImage) VALUES
(1, 'Air Conditioner', 'LG', 450, 1, 1, 'Plastic', '2023', 30.50, 20, 'lg_air_conditioner.jpg'),
(2, 'Dehumidifier', 'Philips', 300, 2, 2, 'Metal', '2022', 25.00, 15, 'philips_dehumidifier.jpg'),
(3, 'Air Purifier', 'Dyson', 350, 3, 3, 'Glass', '2021', 18.50, 25, 'dyson_air_purifier.jpg'),
(4, 'Fan', 'Panasonic', 120, 4, 4, 'Plastic', '2023', 5.00, 30, 'panasonic_fan.jpg'),
(5, 'Heater', 'Xiaomi', 200, 5, 5, 'Metal', '2022', 12.00, 10, 'xiaomi_heater.jpg'),
(6, 'Cooler', 'Sharp', 400, 1, 1, 'Plastic', '2023', 28.00, 18, 'sharp_cooler.jpg'),
(7, 'Portable AC', 'Samsung', 500, 2, 2, 'Metal', '2021', 32.00, 12, 'samsung_portable_ac.jpg');



INSERT INTO pico.television(ID, ProductName, ProductBrand, ProductPrice, ProductSize, ProductOrigin, ProductMaterial, ProductYear, ProductWeight, ProductQuantity, ProductImage) VALUES
(23, 'Sony Bravia X90J', 1, 1200, 55, 1, 'Plastic', '2023', 20.50, 10, 'sony_bravia_x90j.jpg'),
(24, 'Samsung QLED Q80T', 2, 1500, 65, 2, 'Metal', '2022', 25.00, 8, 'samsung_qled_q80t.jpg'),
(25, 'LG OLED CX', 3, 1800, 55, 3, 'Glass', '2021', 22.00, 12, 'lg_oled_cx.jpg'),
(26, 'Panasonic TX-55HX800', 4, 1000, 55, 4, 'Plastic', '2023', 19.00, 15, 'panasonic_tx_55hx800.jpg'),
(27, 'Philips Ambilight 4K', 5, 1300, 50, 5, 'Metal', '2022', 21.00, 11, 'philips_ambilight_4k.jpg'),
(28, 'Sony A8H OLED', 6, 2000, 65, 1, 'Glass', '2023', 24.00, 9, 'sony_a8h_oled.jpg'),
(29, 'Samsung Frame TV', 7, 1600, 55, 2, 'Plastic', '2022', 23.00, 10, 'samsung_frame_tv.jpg'),
(30, 'LG NanoCell 90', 8, 1400, 65, 3, 'Metal', '2021', 26.00, 7, 'lg_nanocell_90.jpg'),
(31, 'TCL 6-Series', 9, 1100, 55, 4, 'Plastic', '2022', 18.00, 14, 'tcl_6_series.jpg'),
(32, 'Vizio P-Series Quantum', 10, 1200, 65, 5, 'Glass', '2023', 20.00, 13, 'vizio_p_series_quantum.jpg');